from __future__ import annotations

ANGULAR_TS_APIS: tuple[str, ...] = (
    "Component",
    "Injectable",
    "Input",
    "Output",
    "Pipe",
    "Directive",
    "inject",
    "signal",
    "computed",
    "effect",
    "input",
    "output",
    "EventEmitter",
    "OnInit",
    "OnDestroy",
    "ChangeDetectionStrategy",
    "standalone",
    "imports",
    "template",
    "templateUrl",
    "styleUrls",
    "styles",
    "providers",
    "selector",
    "bootstrapApplication",
    "provideRouter",
    "provideHttpClient",
    "HttpClient",
    "HttpInterceptorFn",
    "FormBuilder",
    "FormControl",
    "FormGroup",
    "Validators",
    "ReactiveFormsModule",
    "FormsModule",
    "CommonModule",
    "NgIf",
    "NgFor",
    "NgClass",
    "AsyncPipe",
    "RouterLink",
    "RouterLinkActive",
    "ActivatedRoute",
    "Routes",
    "Route",
    "CanActivateFn",
    "CanDeactivateFn",
    "ResolveFn",
    "Observable",
    "of",
    "map",
    "switchMap",
    "debounceTime",
    "distinctUntilChanged",
    "import { Component } from '@angular/core'",
    "import { inject } from '@angular/core'",
    "import { signal, computed } from '@angular/core'",
    "import { CommonModule } from '@angular/common'",
    "import { FormsModule, ReactiveFormsModule } from '@angular/forms'",
    "import { provideRouter, RouterLink } from '@angular/router'",
    "import { provideHttpClient, HttpClient } from '@angular/common/http'",
    "import { bootstrapApplication } from '@angular/platform-browser'",
    "import { Observable, of } from 'rxjs'",
    "import { map, switchMap } from 'rxjs/operators'",
)

PYTHON_APIS: tuple[str, ...] = (
    "def",
    "class",
    "import",
    "from",
    "return",
    "self",
    "if",
    "elif",
    "else",
    "for",
    "while",
    "with",
    "as",
    "try",
    "except",
    "finally",
    "raise",
    "yield",
    "lambda",
    "pass",
    "break",
    "continue",
    "True",
    "False",
    "None",
    "and",
    "or",
    "not",
    "in",
    "is",
    "len",
    "range",
    "print",
    "str",
    "int",
    "float",
    "bool",
    "list",
    "dict",
    "set",
    "tuple",
    "enumerate",
    "zip",
    "map",
    "filter",
    "sorted",
    "isinstance",
    "super",
    "staticmethod",
    "classmethod",
    "property",
    "dataclass",
    "Optional",
    "Union",
    "List",
    "Dict",
    "Set",
    "Tuple",
    "Any",
    "__init__",
    "__name__",
    "__main__",
)

PHP_APIS: tuple[str, ...] = (
    "function",
    "class",
    "interface",
    "trait",
    "enum",
    "namespace",
    "use",
    "public",
    "private",
    "protected",
    "readonly",
    "static",
    "final",
    "abstract",
    "extends",
    "implements",
    "return",
    "echo",
    "print",
    "if",
    "elseif",
    "else",
    "foreach",
    "for",
    "while",
    "switch",
    "case",
    "default",
    "break",
    "continue",
    "try",
    "catch",
    "finally",
    "throw",
    "new",
    "true",
    "false",
    "null",
    "array",
    "string",
    "int",
    "float",
    "bool",
    "mixed",
    "void",
    "never",
    "match",
    "fn",
    "declare",
    "strict_types",
    "self",
    "parent",
    "static",
    "__construct",
    "__invoke",
    "compact",
    "count",
    "array_map",
    "array_filter",
    "in_array",
    "json_encode",
    "json_decode",
    "strlen",
    "substr",
    "explode",
    "implode",
    "trim",
    "isset",
    "empty",
    "unset",
)


def normalize_editor_language(language: str) -> str:
    lang = (language or "typescript").strip().lower()
    mapping = {
        "typescript": "typescript",
        "ts": "typescript",
        "javascript": "javascript",
        "js": "javascript",
        "python": "python",
        "py": "python",
        "php": "php",
        "html": "html",
        "css": "css",
        "json": "json",
        "sql": "sql",
        "shell": "shell",
        "bash": "shell",
    }
    return mapping.get(lang, "plaintext")


def completion_items(language: str) -> tuple[str, ...]:
    lang = normalize_editor_language(language)
    if lang in ("typescript", "javascript"):
        return ANGULAR_TS_APIS
    if lang == "python":
        return PYTHON_APIS
    if lang == "php":
        return PHP_APIS
    return ()
